# Generated by Django 3.0.2 on 2020-01-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name_plural': 'Areas'},
        ),
    ]
